$schema: https://azuremlschemas.azureedge.net/promptflow/latest/Flow.schema.json
environment:
  python_requirements_txt: requirements.txt
inputs:
  chat_history:
    type: list
    is_chat_history: true
    default: []
  question:
    type: string
    is_chat_input: true
    default: >-
      23. LIMITATION OF LIABILITY  (a) Nothing shall limit the Seller’s
      responsibility to the Buyer regarding any claim to the extent arising
      from:  (i) death, injury or property damage to third parties;  (ii)
      failure of the Seller to comply with applicable laws and
      regulations;  (iii) fraud, negligence or wilful misconduct;  (iv)
      intellectual property infringement or misuse or misappropriation of
      intellectual property; or  (v) intentional breach of the Contract.  (b)
      The Buyer will not be responsible in any way to the Seller or any third
      party (whether arising in contract,  tort or otherwise) for any special,
      indirect, consequential and incidental losses or damag

      28. CHOICE OF LAW AND DISPUTE RESOLUTION (a) The Contract shall be governed by and construed in accordance with the laws of Singapore, without reference to its conflict of laws rules. (b) For Purchase Orders issued to Sellers incorporated in Singapore, unless otherwise specified in the Purchase Order, the parties submit to the jurisdiction of the courts of Singapore. (c) For Purchase Orders issued to Sellers other than those described in Clause 28(b) above, unless otherwise specified in the Purchase Order, any dispute arising out of or in connection with the Contract, including any question regarding its existence, validity or termination, shall be referred to and finally resolved by arbitration in Singapore in accordance with the Arbitration Rules of the Singapore International Arbitration Centre (SIAC) for the time being in force, which rules are deemed to be incorporated by reference into this Clause. The arbitration proceedings shall be conducted in English. The arbitration award shall be enforceable before a court of competent jurisdiction. (d) For the avoidance of doubt, parties are not precluded from seeking injunctive relief from a court of competent jurisdiction in relation to any breach or threatened breach of the Contract to avoid irreparable harm or injury. 
  query_type:
    type: int
    default: 1
  selection:
    type: string
    default: The Contract shall be governed by and construed in accordance with the
      laws of Singapore
outputs:
  answer:
    type: string
    reference: ${selection_summary.output} ${selection_summary.output}
    is_chat_output: true
nodes:
- name: list_policys
  type: python
  source:
    type: code
    path: list_policys.py
  inputs:
    searchconnection: azuresearch
    input: ${inputs.question}
  activate:
    when: ${inputs.query_type}
    is: 0
- name: summary_document
  type: python
  source:
    type: code
    path: summary_document.py
  inputs:
    openai: lioropenaitest
    input_text: ${inputs.question}
    policy_list: ${list_policys.output}
- name: selection_summary
  type: python
  source:
    type: code
    path: documen_summary.py
  inputs:
    openai: lioropenaitest
    policy_list: ${search_policy.output}
    input_text: ${inputs.selection}
- name: search_policy
  type: python
  source:
    type: code
    path: search_policy.py
  inputs:
    searchconnection: azuresearch
    embeding: ${text_embedding.output}
- name: text_embedding
  type: python
  source:
    type: package
    tool: promptflow.tools.embedding.embedding
  inputs:
    connection: lioropenaitest
    deployment_name: ada002
    input: ${inputs.selection}
  activate:
    when: ${inputs.query_type}
    is: 2
