id: template_standard_flow
name: Template Standard Flow
inputs:
  input:
    type: object
    is_chat_input: false
outputs:
  out:
    type: string
    reference: ${ReWrite.output}
nodes:
- name: clasification
  type: python
  source:
    type: code
    path: echo.py
  inputs:
    input: ${inputs.input}
  use_variants: false
- name: GeneralQuestion
  type: llm
  source:
    type: code
    path: GeneralQuestion.jinja2
  inputs:
    deployment_name: gpt4o-mini
    temperature: 1
    top_p: 1
    max_tokens: 500
    response_format:
      type: text
    question: ${clasification.output.query}
    selection: ${clasification.output.input}
  provider: AzureOpenAI
  connection: gbbailiortestopenai1
  api: chat
  module: promptflow.tools.aoai
  use_variants: false
- name: queryEmbeding
  type: python
  source:
    type: package
    tool: promptflow.tools.embedding.embedding
  inputs:
    connection: gbbailiortestopenai1
    deployment_name: ada002
    input: ${clasification.output.query}
  use_variants: false
- name: SearchPolicy
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://gbbailiortestopenai1.openai.azure.com/
        api_type: azure
        api_version: 2023-07-01-preview
        batch_size: '1'
        connection:
          id: /subscriptions/9e03f5fd-74b3-4bb5-9a11-b1c93dd4a48b/resourceGroups/GBBAI/providers/Microsoft.MachineLearningServices/workspaces/liorarmiev-9524/connections/gbbailiortestopenai1
        connection_type: workspace_connection
        deployment: ada002
        dimension: 1536
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: 2024-05-01-preview
        connection:
          id: /subscriptions/9e03f5fd-74b3-4bb5-9a11-b1c93dd4a48b/resourceGroups/GBBAI/providers/Microsoft.MachineLearningServices/workspaces/liorarmiev-9524/connections/gbbsearchtest1
        connection_type: workspace_connection
        endpoint: https://gbbsearchtest1.search.windows.net/
        engine: azure-sdk
        field_mapping:
          content: instruction
          embedding: embeding
          metadata: title
        index: legal-instructions
        kind: acs
        semantic_configuration_name: null
    queries: ${clasification.output.query}
    query_type: Vector
    top_k: 3
  use_variants: false
- name: ReWrite
  type: prompt
  source:
    type: code
    path: ReWrite.jinja2
  inputs:
    input: ${clasification.output.input}
    policy: ${SearchPolicy.output}
  use_variants: false
node_variants: {}
environment:
  python_requirements_txt: requirements.txt
